# Generated by Django 4.0.3 on 2022-03-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='obchodni_pripad',
            field=models.DecimalField(decimal_places=2, default=0.45, max_digits=6),
        ),
    ]
